version: '3.8'

services:

  mysql:
    image: mysql
    container_name: shop-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=shop_api
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - "8089:80"
